-- scripts/db/mark-applied.sql — generated by scripts/db/gen-legacy-dbmate-migrations.mjs
--
-- Marks the 79 legacy migrations (supabase/migrations/001…078, already
-- applied to production by psql) as applied in dbmate's table, so that
-- `dbmate status` shows them as done and `dbmate up` only runs NEW files.
--
-- NOT RUN IN PRODUCTION YET. Procedure (docs/migrations.md):
--   1. dump the production schema and diff it against db/schema.sql
--   2. only if the diff is empty:
--      docker exec -i supabase-db psql -U postgres -d proj_billing -v ON_ERROR_STOP=1 < scripts/db/mark-applied.sql
-- Idempotent: re-running inserts nothing new.

CREATE TABLE IF NOT EXISTS public.schema_migrations (version character varying NOT NULL PRIMARY KEY);

INSERT INTO public.schema_migrations (version) VALUES
  ('20000101000001'),  -- 001_auth_tables.sql
  ('20000101000002'),  -- 002_debtors.sql
  ('20000101000003'),  -- 003_debtor_panel.sql
  ('20000101000004'),  -- 004_completed_actions.sql
  ('20000101000005'),  -- 005_status_management.sql
  ('20000101000006'),  -- 006_app_settings.sql
  ('20000101000007'),  -- 007_roles_and_permissions.sql
  ('20000101000008'),  -- 008_simplify_permissions.sql
  ('20000101000009'),  -- 009_invite_custom_permissions.sql
  ('20000101000010'),  -- 010_security_phase0.sql
  ('20000101000011'),  -- 011_suppliers.sql
  ('20000101000012'),  -- 012_debtor_archived_at.sql
  ('20000101000013'),  -- 013_debtor_events.sql
  ('20000101000014'),  -- 014_whatsapp.sql
  ('20000101000015'),  -- 015_phone_cleanup.sql
  ('20000101000016'),  -- 016_supplier_categories.sql
  ('20000101000017'),  -- 017_sync_runs.sql
  ('20000101000018'),  -- 018_whatsapp_chat_inbox.sql
  ('20000101000019'),  -- 019_whatsapp_avatars.sql
  ('20000101000020'),  -- 020_whatsapp_instances.sql
  ('20000101000021'),  -- 021_contacts.sql
  ('20000101000022'),  -- 022_import_runs_kind.sql
  ('20000101000023'),  -- 023_tasks_notifications_reminders.sql
  ('20000101000024'),  -- 024_issues.sql
  ('20000101000025'),  -- 025_calendar.sql
  ('20000101000026'),  -- 026_internal_chat.sql
  ('20000101000027'),  -- 027_calendar_external_participants.sql
  ('20000101000028'),  -- 028_tasks_completed_at_related_entity.sql
  ('20000101000029'),  -- 029_audit_log.sql
  ('20000101000030'),  -- 030_user_reminders.sql
  ('20000101000031'),  -- 031_documents.sql
  ('20000101000032'),  -- 032_reminder_categories.sql
  ('20000101000033'),  -- 033_notifications_fanout.sql
  ('20000101000034'),  -- 034_notifications_clear.sql
  ('20000101000035'),  -- 035_user_invites_allow_super_admin.sql
  ('20000101000036'),  -- 036_users_allow_google_auth.sql
  ('20000101000037'),  -- 037_areas.sql
  ('20000101000038'),  -- 038_areas_type_color.sql
  ('20000101000039'),  -- 039_areas_drop_responsible_contact.sql
  ('20000101000040'),  -- 040_tasks_issues_target.sql
  ('20000101000041'),  -- 041_manager_full_access.sql
  ('20000101000042'),  -- 042_vendors.sql
  ('20000101000043'),  -- 043_drop_vendors.sql
  ('20000101000044'),  -- 044_issues_supplier.sql
  ('20000101000045'),  -- 045_tasks_supplier.sql
  ('20000101000046'),  -- 046_suppliers_status_archive.sql
  ('20000101000047'),  -- 047_entity_assignees.sql
  ('20000101000048'),  -- 048_reminders_whatsapp_channel.sql
  ('20000101000049'),  -- 049_reminders_channels_multi.sql
  ('20000101000050'),  -- 050_issues_sort_order.sql
  ('20000101000051'),  -- 051_chat_messages_supplier.sql
  ('20000101000052'),  -- 052_supplier_categories_color.sql
  ('20000101000053'),  -- 053_tasks_recurrence.sql
  ('20000101000054'),  -- 054_issues_due_date.sql
  ('20000101000055'),  -- 055_backfill_recurrence_anchor.sql
  ('20000101000056'),  -- 056_monthly_debt_snapshots.sql
  ('20000101000057'),  -- 057_session_id_hash.sql
  ('20000101000058'),  -- 058_chat_presence.sql
  ('20000101000059'),  -- 059_whatsapp_delivery_queue.sql
  ('20000101000060'),  -- 060_chat_messages_attachment.sql
  ('20000101000061'),  -- 061_debtor_collection_tracking.sql
  ('20000101000062'),  -- 062_whatsapp_instances_user_id_comment.sql
  ('20000101000063'),  -- 063_chat_messages_media_url_rehost.sql
  ('20000101000064'),  -- 063_worker_roles.sql
  ('20000101000065'),  -- 064_issues_videos.sql
  ('20000101000066'),  -- 065_reminders_notify_owner.sql
  ('20000101000067'),  -- 066_contact_people_and_apartment_fields.sql
  ('20000101000068'),  -- 067_recurrence_single_instance.sql
  ('20000101000069'),  -- 068_remove_orphaned_task_notifications.sql
  ('20000101000070'),  -- 069_remove_orphaned_issue_notifications.sql
  ('20000101000071'),  -- 070_normalize_source_entity_type.sql
  ('20000101000072'),  -- 071_contacts_registry.sql
  ('20000101000073'),  -- 072_chips.sql
  ('20000101000074'),  -- 073_import_runs_error_summary.sql
  ('20000101000075'),  -- 074_chips_holder_identity_search.sql
  ('20000101000076'),  -- 075_seed_qa_viewer.sql
  ('20000101000077'),  -- 076_parking_storage.sql
  ('20000101000078'),  -- 077_seed_parking_1P.sql
  ('20000101000079')  -- 078_legal_contact_setting.sql
ON CONFLICT (version) DO NOTHING;
