-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/043_drop_vendors.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 043_drop_vendors.sql
-- Reversal of 042_vendors.sql. The standalone `vendors` module was removed in
-- favour of the existing heavyweight `suppliers` module as the single supplier
-- directory.
--
-- This is a forward, additive migration — it does NOT edit 042 (which already
-- ran on proj_billing). Running 042 then 043 nets to "no vendors", and on the
-- live DB only 043 needs to run. Idempotent (IF EXISTS + an unconditional delete).
--
-- Run: docker exec -i supabase-db psql -U postgres -d proj_billing < supabase/migrations/043_drop_vendors.sql

begin;

-- Remove the RBAC rows for the dropped module (manager/viewer backfill from 042).
delete from public.user_permissions where module = 'vendors';

-- Drop the tables — vendors first (it FKs vendor_categories).
drop table if exists public.vendors;
drop table if exists public.vendor_categories;

commit;

-- migrate:down
-- no down migration was written for legacy 043_drop_vendors
