-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/067_recurrence_single_instance.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 067_recurrence_single_instance.sql
-- Recurrence model change: HORIZON/materialization → SINGLE ROW.
--
-- Before: a recurring task was a TEMPLATE plus one materialized INSTANCE row per
-- occurrence, 45 days ahead (materializeDue, re-run on every /tasks load). A daily
-- task = ~45 rows; a 3-day weekly task = ~20 rows. The board and the lane counts
-- were flooded with the same task over and over.
--
-- After: a recurring task is exactly ONE tasks row.
--   * tasks.due_date        = the CURRENT occurrence. Advances on completion/skip.
--   * task_recurrences.anchor_date = the series origin (immutable). Interval and
--     `after_count` math are measured from here, so advancing due_date never
--     re-phases the series.
--   * task_occurrence_completions = one row per completed occurrence (the history
--     that due_date no longer carries), which also drives the "1/3 השבוע" badge.
--
-- Destructive by design (agreed with the product owner): every materialized
-- instance row is deleted. Past completion history is NOT converted — the
-- completions log starts empty.
--
-- Run (DIRECT_URL, direct port 5432, for DDL):
--   psql "$DIRECT_URL" -f supabase/migrations/067_recurrence_single_instance.sql

begin;

-- ── 1. The series anchor moves onto the RULE ────────────────────────────────
-- It used to live in tasks.occurrence_date (see migration 055). That column now
-- has nothing left to mean, because due_date is the live occurrence pointer.
alter table public.task_recurrences
  add column if not exists anchor_date date null;

-- Backfill: the template's old anchor, falling back to its due date and finally
-- to its creation day (Asia/Jerusalem — the app's date convention, same fallback
-- migration 055 used for date-less series).
update public.task_recurrences r
   set anchor_date = coalesce(
         t.occurrence_date,
         t.due_date,
         (t.created_at at time zone 'Asia/Jerusalem')::date
       )
  from public.tasks t
 where t.id = r.task_id
   and r.anchor_date is null;

-- Rules whose owning task vanished (FK is CASCADE, so this should be empty —
-- belt and braces so the NOT NULL below can never fail).
update public.task_recurrences
   set anchor_date = (created_at at time zone 'Asia/Jerusalem')::date
 where anchor_date is null;

alter table public.task_recurrences
  alter column anchor_date set not null;

-- ── 2. Completion log ───────────────────────────────────────────────────────
-- One row per occurrence actually marked done. Survives the series row being
-- re-scheduled (that is the whole point) and cascades away with the task.
create table if not exists public.task_occurrence_completions (
  id                uuid primary key default gen_random_uuid(),
  task_id           uuid not null references public.tasks(id) on delete cascade,
  recurrence_id     uuid null references public.task_recurrences(id) on delete set null,
  occurrence_date   date not null,
  completed_at      timestamptz not null default now(),
  completed_by      uuid null references public.users(id) on delete set null,
  completed_by_name text null,
  -- Completing the same occurrence twice is a no-op, not a duplicate row.
  unique (task_id, occurrence_date)
);

-- The per-period aggregate ("done this week") scans by task + recent dates.
create index if not exists task_occurrence_completions_task_date_idx
  on public.task_occurrence_completions (task_id, occurrence_date desc);
create index if not exists task_occurrence_completions_recurrence_idx
  on public.task_occurrence_completions (recurrence_id);

-- ── 3. Point each series row at its correct current occurrence ──────────────
-- The materializer already created a row for every occurrence in the next 45
-- days, so the earliest open instance on/after today IS the next occurrence.
-- Templates already sitting on a today-or-future date keep it; date-less
-- templates (migration 055) fall back to the anchor.
update public.tasks t
   set due_date = coalesce(
         (select min(i.occurrence_date)
            from public.tasks i
           where i.recurrence_id = t.recurrence_id
             and i.is_recurring_instance = true
             and i.is_archived = false
             and i.status in ('open', 'in_progress')
             and i.occurrence_date >= current_date),
         t.due_date,
         r.anchor_date
       )
  from public.task_recurrences r
 where r.id = t.recurrence_id
   and t.is_recurring_instance = false
   and (t.due_date is null or t.due_date < current_date);

-- ── 4. Delete every materialized instance ──────────────────────────────────
-- entity_assignees (047) and reminders (023) are POLYMORPHIC — entity_id has no
-- FK to tasks — so they need explicit deletes, child rows first. notifications
-- are cleaned too so the bell never links to a deleted task. task_comments
-- cascade via their FK.
delete from public.entity_assignees ea
 where ea.entity_type = 'task'
   and ea.entity_id in (select id from public.tasks where is_recurring_instance = true);

delete from public.reminders rm
 where rm.entity_type = 'task'
   and rm.entity_id in (select id from public.tasks where is_recurring_instance = true);

delete from public.notifications n
 where n.source_entity_type = 'task'
   and n.source_entity_id in (select id from public.tasks where is_recurring_instance = true);

delete from public.tasks where is_recurring_instance = true;

-- ── 5. "One row per series" becomes a real constraint ───────────────────────
-- Defensive: if any non-instance duplicate still shares a recurrence_id, keep
-- the row the rule actually points at and detach the rest (rather than aborting).
update public.tasks t
   set recurrence_id = null,
       is_recurring_template = false
 where t.recurrence_id is not null
   and not exists (
     select 1 from public.task_recurrences r
      where r.id = t.recurrence_id and r.task_id = t.id
   );

drop index if exists public.tasks_recurrence_occurrence_uniq;

create unique index if not exists tasks_recurrence_single_row_uniq
  on public.tasks (recurrence_id)
  where recurrence_id is not null;

-- ── 6. Retire the instance-model columns ───────────────────────────────────
-- Kept in the schema (frozen, like tasks.assigned_to_user_id / supplier_id) so
-- this migration stays non-destructive at the schema level. The app no longer
-- reads or writes them.
update public.tasks
   set occurrence_date       = null,
       parent_task_id        = null,
       is_recurring_instance = false,
       is_recurring_template = (recurrence_id is not null)
 where recurrence_id is not null
    or occurrence_date is not null
    or parent_task_id is not null
    or is_recurring_instance = true
    or is_recurring_template = true;

comment on column public.tasks.occurrence_date is
  'FROZEN (migration 067): superseded by the single-row model — due_date is the current occurrence.';
comment on column public.tasks.is_recurring_instance is
  'FROZEN (migration 067): always false — there are no materialized instances any more.';
comment on column public.tasks.parent_task_id is
  'FROZEN (migration 067): instances no longer exist, so nothing points at a parent task.';
comment on column public.task_recurrences.last_spawned_at is
  'FROZEN (migration 067): the materializer is gone.';
comment on column public.task_recurrences.spawned_count is
  'FROZEN (migration 067): the materializer is gone.';
comment on column public.task_recurrences.anchor_date is
  'Series origin (immutable). interval / after_count are measured from here, so advancing tasks.due_date never re-phases the series.';

commit;

-- migrate:down
-- no down migration was written for legacy 067_recurrence_single_instance
