-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/007_roles_and_permissions.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 007_roles_and_permissions.sql
-- Slice 6 — RBAC: replace boolean is_admin with role + per-module permission matrix.

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- users: add role + is_active. Existing is_admin=true users are
-- promoted to super_admin; everyone else lands on the column default
-- ('viewer') and is_active stays true.
-- ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'viewer';

ALTER TABLE public.users
  ADD CONSTRAINT users_role_check
  CHECK (role IN ('super_admin','admin','manager','viewer'));

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

UPDATE public.users SET role = 'super_admin' WHERE is_admin = true;

ALTER TABLE public.users DROP COLUMN IF EXISTS is_admin;

-- ─────────────────────────────────────────────────────────────────────
-- user_permissions: matrix for manager/viewer (super_admin/admin
-- are hardcoded in code and never have rows here).
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_permissions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  module      text NOT NULL,
  can_view    boolean NOT NULL DEFAULT false,
  can_edit    boolean NOT NULL DEFAULT false,
  can_delete  boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, module)
);

CREATE INDEX IF NOT EXISTS idx_user_permissions_user
  ON public.user_permissions (user_id);

DROP TRIGGER IF EXISTS user_permissions_touch_updated_at ON public.user_permissions;
CREATE TRIGGER user_permissions_touch_updated_at
  BEFORE UPDATE ON public.user_permissions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────
-- user_invites: pending invites, become a users row on accept.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.user_invites (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email       text NOT NULL,
  full_name   text NOT NULL,
  role        text NOT NULL CHECK (role IN ('admin','manager','viewer')),
  token       text NOT NULL UNIQUE,
  invited_by  uuid NOT NULL REFERENCES public.users(id),
  expires_at  timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_user_invites_token       ON public.user_invites (token);
CREATE INDEX IF NOT EXISTS idx_user_invites_email_lower ON public.user_invites (lower(email));

COMMIT;

-- migrate:down
-- no down migration was written for legacy 007_roles_and_permissions
