-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/022_import_runs_kind.sql — do not edit; edit nothing, history is frozen.
-- migrate:up
-- 022_import_runs_kind.sql
-- Slice 4 Track C — make import_runs serve BOTH the debtors import and the new
-- contacts (residents) Excel import. Additive + idempotent.
--
--   * kind        — discriminator between the two import pipelines.
--   * file_name   — original upload name (contacts import shows it in history).
--   * failed_rows — per-row failure counter (debtors import doesn't use it → 0).
--   * error_details — jsonb array of failed rows (contacts import).
--   * status CHECK widened to a SUPERSET — existing debtors statuses
--     (running/success/error) stay valid; the new contacts lifecycle states are
--     added. Debtors code is unaffected (it only ever writes the old three).
--
-- Run: psql "$DIRECT_URL" -f supabase/migrations/022_import_runs_kind.sql

alter table public.import_runs add column if not exists kind text not null default 'debtors';
alter table public.import_runs add column if not exists file_name text;
alter table public.import_runs add column if not exists failed_rows integer not null default 0;
alter table public.import_runs add column if not exists error_details jsonb;

alter table public.import_runs drop constraint if exists import_runs_kind_check;
alter table public.import_runs add  constraint import_runs_kind_check
  check (kind in ('debtors', 'contacts'));

-- Widen the status check to a superset (debtors: running/success/error;
-- contacts: parsing/processing/completed/partial/failed).
alter table public.import_runs drop constraint if exists import_runs_status_check;
alter table public.import_runs add  constraint import_runs_status_check
  check (status in (
    'running', 'success', 'error',
    'parsing', 'processing', 'completed', 'partial', 'failed'
  ));

create index if not exists idx_import_runs_kind on public.import_runs (kind);

-- migrate:down
-- no down migration was written for legacy 022_import_runs_kind
