-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/023_tasks_notifications_reminders.sql — do not edit; edit nothing, history is frozen.
-- migrate:up
-- 023_tasks_notifications_reminders.sql
-- Module 1 — Tasks + Notifications infrastructure + generic Reminders engine.
--
-- ADDITIVE ONLY. Creates four new tables; touches no existing table beyond
-- adding indexes on its own new tables. Idempotent (IF NOT EXISTS /
-- CREATE OR REPLACE) — safe to re-run. No data is deleted or migrated.
--
-- status / priority are stored as text with CHECK constraints (project
-- convention — see statuses/import_runs — avoids hard pg ENUM migrations).
--
-- Run: psql "$DIRECT_URL" -f supabase/migrations/023_tasks_notifications_reminders.sql

-- ─────────────────────────────────────────────────────────────────────────
-- 1. tasks
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.tasks (
  id                 uuid primary key default gen_random_uuid(),
  title              text not null,
  description        text,
  status             text not null default 'open'
                       check (status in ('open', 'in_progress', 'done', 'cancelled')),
  priority           text not null default 'normal'
                       check (priority in ('low', 'normal', 'high', 'urgent')),
  due_date           date,
  due_time           time,
  assigned_to_user_id uuid references public.users(id) on delete set null,
  debtor_id          uuid references public.debtors(id) on delete set null,
  apartment_number   text,
  sort_order         integer not null default 0,
  is_archived        boolean not null default false,
  created_by         uuid references public.users(id) on delete set null,
  created_by_name    text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists tasks_status_idx       on public.tasks (status);
create index if not exists tasks_assigned_to_idx   on public.tasks (assigned_to_user_id);
create index if not exists tasks_due_date_idx       on public.tasks (due_date);
-- kanban ordering: cheap per-column sort.
create index if not exists tasks_status_sort_idx    on public.tasks (status, sort_order);

drop trigger if exists tasks_touch_updated_at on public.tasks;
create trigger tasks_touch_updated_at
  before update on public.tasks
  for each row execute function public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- 2. task_comments
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.task_comments (
  id           uuid primary key default gen_random_uuid(),
  task_id      uuid not null references public.tasks(id) on delete cascade,
  content      text not null,
  author_id    uuid references public.users(id) on delete set null,
  author_name  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists task_comments_task_id_idx on public.task_comments (task_id, created_at);

drop trigger if exists task_comments_touch_updated_at on public.task_comments;
create trigger task_comments_touch_updated_at
  before update on public.task_comments
  for each row execute function public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- 3. notifications (per-user, in-app)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.notifications (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references public.users(id) on delete cascade,
  type                text not null,
  title               text not null,
  message             text,
  is_read             boolean not null default false,
  source_module       text,
  source_entity_type  text,
  source_entity_id    uuid,
  action_url          text,
  priority            text not null default 'normal'
                        check (priority in ('low', 'normal', 'high', 'urgent')),
  dedupe_key          text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- Fast unread-count + listing per user.
create index if not exists notifications_user_read_idx on public.notifications (user_id, is_read);
create index if not exists notifications_user_created_idx on public.notifications (user_id, created_at desc);
-- Partial unique index: dedupe only when a key is supplied.
create unique index if not exists notifications_dedupe_key_uidx
  on public.notifications (dedupe_key)
  where dedupe_key is not null;

drop trigger if exists notifications_touch_updated_at on public.notifications;
create trigger notifications_touch_updated_at
  before update on public.notifications
  for each row execute function public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- 4. reminders (generic — will also serve the future calendar)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.reminders (
  id           uuid primary key default gen_random_uuid(),
  entity_type  text not null,
  entity_id    uuid not null,
  user_id      uuid not null references public.users(id) on delete cascade,
  remind_at    timestamptz not null,
  channel      text not null default 'both'
                 check (channel in ('in_app', 'email', 'both')),
  sent_at      timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- The reminders engine scans only un-sent, due rows — keep that lookup tiny.
create index if not exists reminders_due_idx
  on public.reminders (remind_at)
  where sent_at is null;
create index if not exists reminders_entity_idx on public.reminders (entity_type, entity_id);

drop trigger if exists reminders_touch_updated_at on public.reminders;
create trigger reminders_touch_updated_at
  before update on public.reminders
  for each row execute function public.touch_updated_at();

-- migrate:down
-- no down migration was written for legacy 023_tasks_notifications_reminders
