-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/066_contact_people_and_apartment_fields.sql — do not edit; edit nothing, history is frozen.
-- migrate:up
-- 066_contact_people_and_apartment_fields.sql
-- Contacts — additional owners/tenants per apartment + two apartment fields.
--
-- ADDITIVE ONLY. Two nullable columns on the existing public.contacts table and
-- ONE new table. ZERO change to any existing column, constraint or index, so
-- every existing read/write path (Excel import, Bllink sync, dashboard,
-- broadcasts) keeps behaving exactly as before.
-- Idempotent (IF NOT EXISTS everywhere) — safe to re-run.
--
-- Why a table and not more columns: the apartment card must accept an UNLIMITED
-- number of extra owners/tenants, each with its own name/phone/email and its own
-- "receives messages" flag. The FIRST owner and the FIRST tenant stay in the
-- existing contacts.owner_* / tenant_* columns (nothing to migrate, sync and
-- import untouched); rows here are the 2nd, 3rd, … person of each role.
--
-- Run: psql "$DIRECT_URL" -f supabase/migrations/066_contact_people_and_apartment_fields.sql

-- UP

-- 1. Apartment fields — size in m² and the agreed monthly management fee.
--    NOTE: distinct from public.debtors.management_fees, which is the SYNCED
--    management-fee DEBT pulled from Bllink/Excel. This one is a manual field on
--    the apartment card and is never touched by an import.
alter table public.contacts
  add column if not exists apartment_size_sqm numeric(10,2),
  add column if not exists management_fee     numeric(12,2);

comment on column public.contacts.apartment_size_sqm is
  'Apartment floor area in square metres (manual field, never written by an import).';
comment on column public.contacts.management_fee is
  'Agreed monthly management fee for the apartment (manual). NOT the synced debt in debtors.management_fees.';

-- 2. Additional owners / tenants (2nd person onward for each role).
create table if not exists public.contact_people (
  id                 uuid primary key default gen_random_uuid(),
  contact_id         uuid not null references public.contacts(id) on delete cascade,
  role               text not null check (role in ('owner', 'tenant')),
  name               text,
  phone              text,
  email              text,
  is_primary_contact boolean not null default true,
  sort_order         integer not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

comment on table public.contact_people is
  'Additional owners/tenants of an apartment. The first person of each role lives in contacts.owner_*/tenant_*; these are the extras. is_primary_contact = receives WhatsApp messages/broadcasts.';

create index if not exists contact_people_contact_id_idx
  on public.contact_people (contact_id, role, sort_order);

-- Recipient resolution (broadcasts / bulk send) reads only the message-receiving
-- rows that actually carry a phone.
create index if not exists contact_people_recipients_idx
  on public.contact_people (contact_id)
  where is_primary_contact and phone is not null;

do $$
begin
  if not exists (
    select 1 from pg_trigger where tgname = 'contact_people_touch_updated_at'
  ) then
    create trigger contact_people_touch_updated_at
      before update on public.contact_people
      for each row execute function touch_updated_at();
  end if;
end $$;

-- DOWN
-- drop table if exists public.contact_people;
-- alter table public.contacts
--   drop column if exists apartment_size_sqm,
--   drop column if exists management_fee;

-- migrate:down
-- no down migration was written for legacy 066_contact_people_and_apartment_fields
