-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/061_debtor_collection_tracking.sql — do not edit; edit nothing, history is frozen.
-- migrate:up
-- 061 — per-debtor collection tracking (two new tables)
--
-- Powers a GROSS "collected in practice" figure for the dashboard chart
-- "גבייה מול חובות לפי חודש". The existing monthly_debt_snapshots (056) only
-- holds the summed debt per month, so "collection" was derived as the NET
-- month-over-month drop — which cancels a debtor who paid against a debtor whose
-- debt grew. These tables let the import hook accrue every per-debtor debt DROP
-- as collection, summed per month.
--
-- Keyed by apartment_number (the debtors table's stable UNIQUE business key),
-- NOT debtors.id — a 'replace' import does `delete from debtors` and re-inserts
-- with fresh ids, so an id-keyed snapshot would be orphaned/wiped every replace.
-- No FK for the same reason (snapshots must survive the replace delete).
--
-- ADDITIVE ONLY. Two new tables, idempotent (IF NOT EXISTS). Touches nothing
-- existing — monthly_debt_snapshots is left completely alone.
--
-- Run: psql "$DIRECT_URL" -f supabase/migrations/061_debtor_collection_tracking.sql

-- ─────────────────────────────────────────────────────────────────────────
-- 1. debtor_debt_snapshots — last known debt per debtor (one row per apartment)
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.debtor_debt_snapshots (
  id                uuid primary key default gen_random_uuid(),
  apartment_number  text not null unique,
  total_debt        numeric(12,2) not null default 0,
  snapshot_at       timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────
-- 2. monthly_collections — accrued gross collection per calendar month
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.monthly_collections (
  id                uuid primary key default gen_random_uuid(),
  year              int not null,
  month             int not null check (month between 1 and 12),
  collected_amount  numeric(12,2) not null default 0,
  updated_at        timestamptz not null default now()
);

-- One row per calendar month — the conflict target for the accrual upsert.
create unique index if not exists monthly_collections_ym_idx
  on public.monthly_collections (year, month);

-- migrate:down
-- no down migration was written for legacy 061_debtor_collection_tracking
