-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/078_legal_contact_setting.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 078_legal_contact_setting.sql
-- Settings → "עורך דין": the lawyer's contact lives in app_settings under
-- key 'legal_contact' as { email, name } — never in code. The legal-status
-- change notification reads it at send time (see
-- src/app/api/debtors/[id]/legal-status/route.ts).
--
-- Seeds the row EMPTY so the value is discoverable in the table; the app also
-- tolerates a missing row (reads as empty = not configured, nothing is sent).
-- Additive only: no schema change, and `on conflict do nothing` never
-- overwrites a value that was already saved through the Settings screen.
--
-- DOWN: 078_legal_contact_setting.down.sql (separate file).
-- Run: psql "$DIRECT_URL" -f supabase/migrations/078_legal_contact_setting.sql

begin;

insert into public.app_settings (key, value)
values ('legal_contact', '{"email": "", "name": ""}'::jsonb)
on conflict (key) do nothing;

commit;

-- migrate:down transaction:false
-- 078_legal_contact_setting.down.sql — reverses 078.
-- Removes the legal_contact row, INCLUDING a value saved through the Settings
-- screen — note it down first if it matters. The app keeps working without
-- the row (reads as "not configured").
-- Run: psql "$DIRECT_URL" -f supabase/migrations/078_legal_contact_setting.down.sql

begin;

delete from public.app_settings where key = 'legal_contact';

commit;
