-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/070_normalize_source_entity_type.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 070_normalize_source_entity_type.sql
-- Normalize notifications.source_entity_type to lower_snake_case.
--
-- WHY
-- The column is polymorphic and had no agreed casing: three producers wrote
-- CamelCase ('Task', 'Issue', 'ChatMessage') and three wrote lowercase ('task',
-- 'issue', 'conversation'). A case-sensitive `= 'task'` in migration 067 then
-- matched only half the rows and stranded 140 notifications (cleaned by 068).
-- Commit 09391c0 (070-A) aligned every producer; this migration brings the
-- existing rows into line so consumers can stop compensating.
--
-- Before → after:
--   ChatMessage  969 → chat_message  969
--   Issue        111 ┐               159
--   issue         48 ┘  issue
--   Task          46 ┐                73
--   task          27 ┘  task
--   conversation   7 → conversation    7   (already correct, untouched)
--   NULL           1 → NULL             1   (preserved, see below)
--                1209 rows total, unchanged — this is an UPDATE, nothing is deleted.
--
-- 'ChatMessage' → 'chat_message', NOT a blind lower(): 'chatmessage' would have
-- created a fresh 969-row split against the 'chat_message' the producer now
-- writes, i.e. the exact bug this migration exists to end. The target matches
-- the chat_messages table and calendar_event, the multi-word value already
-- reaching this column from reminders.entity_type.
--
-- NULL is preserved deliberately: source_entity_type is nullable by design for
-- notifications that have no source entity at all (type='system_announcement').
-- Any future CHECK must therefore read
--   source_entity_type is null or source_entity_type = lower(source_entity_type)
--
-- SCOPE — data only. No CHECK constraint (deliberately deferred: producers were
-- only aligned today and none of the three has emitted a row in production yet),
-- and no producer is touched here — that was 070-A.
--
-- Consumers keep their case-insensitive comparisons for now. After this runs
-- they are redundant, not wrong, and removing them is a separate change that
-- should wait until the CHECK makes the invariant enforced rather than merely
-- true.
--
-- Run (DIRECT_URL, direct port 5432):
--   psql "$DIRECT_URL" -f supabase/migrations/070_normalize_source_entity_type.sql
--
-- ROLLBACK — there is no automatic down migration. Every row's previous value is
-- dumped as {"id":…,"v":…} at
--   /var/backups/billing/070/source-entity-type-before.jsonl  (1209 rows, root:0600)
-- Restoring means updating each id back to its recorded `v`.

begin;

update public.notifications
   set source_entity_type =
         case when source_entity_type = 'ChatMessage' then 'chat_message'
              else lower(source_entity_type) end
 where source_entity_type is not null
   and source_entity_type <>
         case when source_entity_type = 'ChatMessage' then 'chat_message'
              else lower(source_entity_type) end;

commit;

-- Idempotent: the WHERE clause skips rows already normalized, so a second run
-- updates 0 rows.

-- migrate:down
-- no down migration was written for legacy 070_normalize_source_entity_type
