-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/025_calendar.sql — do not edit; edit nothing, history is frozen.
-- migrate:up
-- 025_calendar.sql
-- Module 3 — Calendar (יומן). Events with participants, recurrence (materialized
-- occurrences), and reminders via the generic reminders engine (023).
--
-- ADDITIVE ONLY. Creates two new tables (calendar_events +
-- calendar_event_participants). Touches no existing table. Idempotent
-- (IF NOT EXISTS / CREATE OR REPLACE) — safe to re-run. No data is deleted.
--
-- color_key / item_kind / status / recurrence_* are stored as text with CHECK
-- constraints (project convention — see tasks/issues/statuses — avoids hard pg
-- ENUM migrations).
--
-- Recurrence model = materialized occurrences: saving a recurring event writes
-- one parent row (recurrence_enabled=true, parent_series_id=null) plus N
-- generated occurrence rows (source_type='generated_occurrence',
-- parent_series_id=parent.id), capped at 78 occurrences OR 18 months ahead.
-- Editing a single occurrence flags it is_exception=true so a series-wide edit
-- skips it. Deleting "this and future" removes only non-exception future
-- occurrences of that exact series.
--
-- Run: psql "$DIRECT_URL" -f supabase/migrations/025_calendar.sql

-- ─────────────────────────────────────────────────────────────────────────
-- 1. calendar_events
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.calendar_events (
  id                   uuid primary key default gen_random_uuid(),
  title                text not null,
  item_kind            text not null default 'meeting'
                         check (item_kind in ('meeting', 'event')),
  event_date           date not null,
  start_datetime       timestamptz,
  end_datetime         timestamptz,
  is_all_day           boolean not null default false,
  location             text,
  description          text,
  color_key            text not null default 'blue',  -- key into DESIGN.md tone palette
  status               text not null default 'scheduled'
                         check (status in ('scheduled', 'completed', 'cancelled')),
  owner_user_id        uuid references public.users(id) on delete set null,

  -- recurrence (only meaningful on the parent / standalone row)
  recurrence_enabled   boolean not null default false,
  recurrence_type      text
                         check (recurrence_type in ('daily', 'weekly', 'monthly', 'yearly')),
  recurrence_interval  integer not null default 1,
  recurrence_end_type  text not null default 'never'
                         check (recurrence_end_type in ('never', 'until_date', 'count')),
  recurrence_until_date date,
  recurrence_count     integer,

  -- materialized-occurrence bookkeeping
  parent_series_id     uuid references public.calendar_events(id) on delete cascade,
  is_exception         boolean not null default false,
  source_type          text not null default 'manual'
                         check (source_type in ('manual', 'generated_occurrence')),

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- Range queries (GET /api/calendar?from&to) scan by event_date.
create index if not exists calendar_events_event_date_idx  on public.calendar_events (event_date);
-- Series operations (edit/delete "this and future") scan by parent.
create index if not exists calendar_events_parent_series_idx on public.calendar_events (parent_series_id);
create index if not exists calendar_events_owner_idx         on public.calendar_events (owner_user_id);

drop trigger if exists calendar_events_touch_updated_at on public.calendar_events;
create trigger calendar_events_touch_updated_at
  before update on public.calendar_events
  for each row execute function public.touch_updated_at();

-- ─────────────────────────────────────────────────────────────────────────
-- 2. calendar_event_participants
-- ─────────────────────────────────────────────────────────────────────────
create table if not exists public.calendar_event_participants (
  id                  uuid primary key default gen_random_uuid(),
  event_id            uuid not null references public.calendar_events(id) on delete cascade,
  participant_source  text not null
                        check (participant_source in ('user', 'contact')),
  participant_id      uuid not null,           -- users.id or contacts.id (no FK — polymorphic)
  display_name_cache  text,
  email_cache         text,
  attendance_status   text not null default 'pending'
                        check (attendance_status in ('pending', 'accepted', 'declined')),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists calendar_event_participants_event_idx
  on public.calendar_event_participants (event_id);
-- Prevent the same participant being added twice to one event.
create unique index if not exists calendar_event_participants_uniq
  on public.calendar_event_participants (event_id, participant_source, participant_id);

drop trigger if exists calendar_event_participants_touch_updated_at on public.calendar_event_participants;
create trigger calendar_event_participants_touch_updated_at
  before update on public.calendar_event_participants
  for each row execute function public.touch_updated_at();

-- migrate:down
-- no down migration was written for legacy 025_calendar
