-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/041_manager_full_access.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 041_manager_full_access.sql
-- Re-seed EXISTING managers' user_permissions to full operational access, matching
-- the new DEFAULT_MANAGER in src/lib/permissions/constants.ts.
--
-- Why this is needed: a manager's effective permissions are read at runtime from
-- public.user_permissions (see getCurrentActor), NOT derived from DEFAULT_MANAGER.
-- DEFAULT_MANAGER is only the seed applied when a role is (re)assigned. So editing
-- constants.ts affects only FUTURE manager assignments — existing managers keep
-- their stored rows until re-seeded. This migration brings them in line.
--
-- Policy: manager = view+edit on every module EXCEPT settings / users_management /
-- roles_management (admin-only — the line that separates manager from admin).
-- Idempotent: safe to re-run (delete + re-insert the full set for every manager).

begin;

delete from public.user_permissions
 where user_id in (select id from public.users where role = 'manager');

insert into public.user_permissions (user_id, module, can_view, can_edit)
select u.id,
       m.module,
       (m.module not in ('settings', 'users_management', 'roles_management')) as can_view,
       (m.module not in ('settings', 'users_management', 'roles_management')) as can_edit
  from public.users u
  cross join (values
    ('analytics'), ('dashboard'), ('contacts'), ('suppliers'), ('whatsapp'),
    ('tasks'), ('issues'), ('calendar'), ('documents'), ('whatsapp_chat'),
    ('internal_chat'), ('user_reminders'), ('import'), ('export'),
    ('status_management'), ('whatsapp_templates'), ('rooms_areas'),
    ('roles_management'), ('users_management'), ('settings')
  ) as m(module)
 where u.role = 'manager';

commit;

-- migrate:down
-- no down migration was written for legacy 041_manager_full_access
