-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/017_sync_runs.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 017_sync_runs.sql
-- Tracks "סנכרון עכשיו" (POST /api/sync/bllink) runs separately from file
-- imports (import_runs). Sync and import are deliberately distinct operations
-- (see PROJECT_CONTEXT Decisions Log) — the dashboard indicator shows the last
-- import (which drives the freshness severity) AND the last sync, side by side.
--
-- Additive only. Run:
--   docker exec -i supabase-db psql -U postgres -d proj_billing < supabase/migrations/017_sync_runs.sql

BEGIN;

CREATE TABLE IF NOT EXISTS public.sync_runs (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  started_at    timestamptz NOT NULL DEFAULT now(),
  finished_at   timestamptz,
  status        text NOT NULL DEFAULT 'running'
                  CHECK (status IN ('running', 'success', 'error')),
  error_message text,
  triggered_by  uuid REFERENCES public.users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS sync_runs_started_idx ON public.sync_runs (started_at DESC);

COMMIT;

-- migrate:down
-- no down migration was written for legacy 017_sync_runs
