-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/046_suppliers_status_archive.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 046_suppliers_status_archive.sql
-- EPIC 1 · Stage 1 — unify the supplier status vocabulary to a single
-- inactive concept: "ארכיון" (archived).
--
-- Before: status ∈ ('active','inactive','archived'). Three terms, two of which
-- ('inactive','archived') meant the same "not in active use" idea, scattered in
-- the UI as "השבת / לא פעיל / ארכיון".
-- After:  status ∈ ('active','archived'). One active state + one archived state.
--
-- Data-preserving: the legacy 'inactive' rows are folded into 'archived' (they
-- are not deleted, just relabelled). The CHECK is then narrowed to the new set.
-- Idempotent — safe to re-run (the UPDATE is a no-op once no 'inactive' remains,
-- and the constraint is dropped-if-exists before being re-added).

begin;

-- 1) Fold the legacy 'inactive' value into the unified 'archived'.
update public.suppliers set status = 'archived' where status = 'inactive';

-- 2) Narrow the CHECK to exactly the unified set (active + archived).
alter table public.suppliers drop constraint if exists suppliers_status_check;
alter table public.suppliers add constraint suppliers_status_check
  check (status in ('active', 'archived'));

commit;

-- migrate:down
-- no down migration was written for legacy 046_suppliers_status_archive
