-- Generated by scripts/db/gen-legacy-dbmate-migrations.mjs from
-- supabase/migrations/068_remove_orphaned_task_notifications.sql — do not edit; edit nothing, history is frozen.
-- migrate:up transaction:false
-- 068_remove_orphaned_task_notifications.sql
-- Cleanup: delete the notification rows that point at tasks which no longer exist.
--
-- WHY THEY EXIST
-- Migration 067 deleted every materialized recurring-task instance (229 rows) and
-- tried to take their notifications with them:
--
--   delete from public.notifications n
--    where n.source_entity_type = 'task'                       -- ← case-SENSITIVE
--      and n.source_entity_id in (select id from public.tasks where is_recurring_instance = true);
--
-- but the producers write `'Task'` (capital T), so that predicate matched nothing
-- and 140 notifications survived their tasks. Proven, not assumed: all 37 task ids
-- the orphans point at appear in the 067 backup of the deleted instances
-- (/var/backups/billing/067/067-instances-backup.jsonl) — 37/37, none from
-- anywhere else. The rows are `task_due_soon` notifications dated 21/06–25/07.
--
-- Effect of leaving them: the bell shows reminders for tasks that cannot be
-- opened, and every consumer that joins back to `tasks` silently drops a row.
--
-- SCOPE — deletion only. This migration does NOT normalize source_entity_type
-- ('Task' → 'task') and does NOT touch any producer; that is a separate, code-side
-- change (see PROJECT_CONTEXT.md TODO). `lower(...)` below is therefore mandatory:
-- it is the exact guard whose absence created these orphans, and it matches both
-- casings so a future producer variant cannot slip past this cleanup either.
--
-- Out of scope on purpose: 6 orphaned `issue` notifications exist as well. They
-- have a different origin (not 067) and are left untouched.
--
-- Run (DIRECT_URL, direct port 5432):
--   psql "$DIRECT_URL" -f supabase/migrations/068_remove_orphaned_task_notifications.sql
--
-- ROLLBACK — there is no automatic down migration. The deleted rows are dumped
-- verbatim (one JSON object per row, all columns) at
--   /var/backups/billing/068/notifications-task-orphans.jsonl   (140 rows, root:0600)
-- Restoring means re-inserting from that file; it is only meaningful together with
-- restoring the tasks themselves, which 067 already deleted.

begin;

delete from public.notifications
 where lower(source_entity_type) = 'task'
   and not exists (select 1 from public.tasks where id = source_entity_id);

commit;

-- Idempotent: a second run deletes 0 rows.

-- migrate:down
-- no down migration was written for legacy 068_remove_orphaned_task_notifications
