-- 077_seed_parking_1P.sql
-- Seed of lot 1P from ref/parking_spots_1P.csv — the 2015 document
-- "הצמדת חניות לדירות" (14.5.2015), transcribed.
--
-- 187 rows, numbered 1..187 with no gaps and no duplicates.
--
-- LOADED VERBATIM. The file carries 9 doubles where the document's summary
-- table states 14, and therefore 196 places against a stated 201. Those five
-- markings are NOT recoverable: the source document encoded doubles as small
-- digits in its notes column, and those digits did not survive OCR. The gap
-- falls 1 in "הוצמדו לדירות שנמכרו" and 4 in "נותרו בבעלות חוף הכרמל".
--
-- Nothing here guesses at them. The /parking summary screen and
-- scripts/check-parking.mjs both compare this data against the document's
-- stated figures and are EXPECTED to report ⚠️ on those two rows and on the
-- total. That is the mechanism working: the discrepancy stays visible until
-- someone recovers the original markings, rather than being quietly papered
-- over by inventing five doubles.
--
-- IDEMPOTENT: `on conflict (lot_code, spot_number) do nothing`. A second run
-- inserts nothing and — crucially — does NOT overwrite manual edits made
-- through the UI after the first run. Re-seeding is therefore safe but is also
-- a no-op: to genuinely re-apply the file, use the Excel import (which upserts
-- deliberately) or delete the rows first.
--
-- Spots 4, 104, 106, 116 and 163 carry the source document's own
-- inconsistencies in their notes, recorded rather than resolved.
--
-- DOWN: 077_seed_parking_1P.down.sql
-- Run: psql "$DIRECT_URL" -f supabase/migrations/077_seed_parking_1P.sql

begin;

insert into public.parking_spots
  (lot_code, spot_number, owner_type, apartment_number, sale_status, size_type, notes)
values
  ('1P', 1, 'apartment', '534', 'none', 'single', null),
  ('1P', 2, 'apartment', '1042', 'none', 'single', null),
  ('1P', 3, 'apartment', '1323', 'none', 'single', null),
  ('1P', 4, 'developer', null, 'none', 'single', 'לפי המסמך: ברוחב כפול, סומנה בטעות 43,44 (כפילות)'),
  ('1P', 5, 'apartment', '1145', 'none', 'single', null),
  ('1P', 6, 'apartment', '945', 'none', 'single', null),
  ('1P', 7, 'apartment', '834', 'none', 'single', null),
  ('1P', 8, 'apartment', '945', 'none', 'single', null),
  ('1P', 9, 'apartment', '1627', 'none', 'single', null),
  ('1P', 10, 'apartment', '1345', 'none', 'single', null),
  ('1P', 11, 'developer', null, 'none', 'single', null),
  ('1P', 12, 'apartment', '934', 'none', 'single', null),
  ('1P', 13, 'developer', null, 'none', 'single', null),
  ('1P', 14, 'apartment', '1234', 'none', 'single', null),
  ('1P', 15, 'apartment', '1234', 'none', 'single', null),
  ('1P', 16, 'apartment', '727', 'none', 'single', null),
  ('1P', 17, 'apartment', '1523', 'none', 'single', null),
  ('1P', 18, 'apartment', '1029', 'none', 'single', null),
  ('1P', 19, 'apartment', '942', 'none', 'single', null),
  ('1P', 20, 'apartment', '1046', 'none', 'single', null),
  ('1P', 21, 'apartment', '1046', 'none', 'single', null),
  ('1P', 22, 'apartment', '1343', 'none', 'single', null),
  ('1P', 23, 'apartment', '1143', 'none', 'single', null),
  ('1P', 24, 'apartment', '529', 'none', 'single', null),
  ('1P', 25, 'apartment', '1429', 'none', 'single', null),
  ('1P', 26, 'apartment', '1218', 'none', 'single', null),
  ('1P', 27, 'apartment', '1045', 'none', 'single', null),
  ('1P', 28, 'apartment', '1529', 'none', 'single', null),
  ('1P', 29, 'apartment', '613', 'none', 'single', null),
  ('1P', 30, 'apartment', '1003', 'none', 'single', null),
  ('1P', 31, 'apartment', '611', 'none', 'single', null),
  ('1P', 32, 'apartment', '1019', 'none', 'single', null),
  ('1P', 33, 'apartment', '602', 'none', 'single', null),
  ('1P', 34, 'apartment', '717', 'none', 'single', null),
  ('1P', 35, 'apartment', '704', 'none', 'single', null),
  ('1P', 36, 'apartment', '501', 'none', 'single', null),
  ('1P', 37, 'apartment', '601', 'none', 'single', null),
  ('1P', 38, 'apartment', '701', 'none', 'single', null),
  ('1P', 39, 'apartment', '1341', 'none', 'double_width', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 40, 'apartment', '915', 'none', 'single', null),
  ('1P', 41, 'developer', null, 'none', 'double_width', null),
  ('1P', 42, 'apartment', '915', 'none', 'single', null),
  ('1P', 43, 'apartment', '909', 'none', 'single', null),
  ('1P', 44, 'apartment', '1304', 'none', 'single', null),
  ('1P', 45, 'developer', null, 'none', 'single', null),
  ('1P', 46, 'apartment', '1221', 'none', 'single', null),
  ('1P', 47, 'apartment', '1202', 'none', 'single', null),
  ('1P', 48, 'developer', null, 'none', 'single', null),
  ('1P', 49, 'developer', null, 'none', 'single', null),
  ('1P', 50, 'developer', null, 'none', 'single', null),
  ('1P', 51, 'developer', null, 'none', 'single', null),
  ('1P', 52, 'developer', null, 'none', 'single', null),
  ('1P', 53, 'developer', null, 'none', 'single', null),
  ('1P', 54, 'developer', null, 'none', 'single', null),
  ('1P', 55, 'apartment', '606', 'none', 'single', null),
  ('1P', 56, 'developer', null, 'none', 'single', null),
  ('1P', 57, 'apartment', '711', 'none', 'single', null),
  ('1P', 58, 'apartment', '1001', 'none', 'single', null),
  ('1P', 59, 'apartment', '1102', 'none', 'single', null),
  ('1P', 60, 'apartment', '1521', 'none', 'single', null),
  ('1P', 61, 'committee', null, 'for_sale', 'single', null),
  ('1P', 62, 'apartment', '1619', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל; בדיקה: מופיע בטבלה 1 בלבד'),
  ('1P', 63, 'apartment', '811', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 64, 'apartment', '512', 'none', 'single', null),
  ('1P', 65, 'apartment', '1213', 'none', 'single', null),
  ('1P', 66, 'apartment', '718', 'none', 'single', null),
  ('1P', 67, 'apartment', '1213', 'none', 'single', null),
  ('1P', 68, 'apartment', '1121', 'none', 'single', null),
  ('1P', 69, 'apartment', '1421', 'none', 'single', null),
  ('1P', 70, 'apartment', '505', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 71, 'apartment', '1015', 'none', 'single', null),
  ('1P', 72, 'apartment', '1619', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 73, 'apartment', '1131', 'none', 'single', null),
  ('1P', 74, 'apartment', '814', 'none', 'single', null),
  ('1P', 75, 'apartment', '605', 'none', 'single', null),
  ('1P', 76, 'apartment', '1013', 'none', 'single', null),
  ('1P', 77, 'apartment', '1518', 'none', 'single', null),
  ('1P', 78, 'apartment', '914', 'none', 'single', null),
  ('1P', 79, 'apartment', '1201', 'none', 'single', null),
  ('1P', 80, 'apartment', '914', 'none', 'single', null),
  ('1P', 81, 'apartment', '613', 'none', 'double_width', null),
  ('1P', 82, 'developer', null, 'none', 'double_width', null),
  ('1P', 83, 'developer', null, 'none', 'double_width', null),
  ('1P', 84, 'developer', null, 'none', 'double_width', null),
  ('1P', 85, 'developer', null, 'none', 'single', null),
  ('1P', 86, 'developer', null, 'none', 'single', null),
  ('1P', 87, 'developer', null, 'none', 'double_width', null),
  ('1P', 88, 'apartment', '1608', 'none', 'single', null),
  ('1P', 89, 'apartment', '933', 'none', 'single', null),
  ('1P', 90, 'apartment', '1608', 'none', 'single', null),
  ('1P', 91, 'apartment', '1620', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 92, 'apartment', '1620', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 93, 'developer', null, 'none', 'single', null),
  ('1P', 94, 'committee', null, 'for_sale', 'single', null),
  ('1P', 95, 'apartment', '1329', 'none', 'single', null),
  ('1P', 96, 'committee', null, 'for_sale', 'single', null),
  ('1P', 97, 'apartment', '718', 'none', 'single', null),
  ('1P', 98, 'committee', null, 'for_sale', 'single', null),
  ('1P', 99, 'apartment', '929', 'none', 'single', null),
  ('1P', 100, 'apartment', '1626', 'none', 'single', null),
  ('1P', 101, 'apartment', '1628', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 102, 'apartment', '1628', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 103, 'apartment', '1440', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 104, 'apartment', '1621', 'none', 'single', 'בדיקה: דירה 1621 לא מופיעה בטבלת המיון לפי דירות'),
  ('1P', 105, 'apartment', '1440', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 106, 'apartment', '1621', 'none', 'single', 'בדיקה: דירה 1621 לא מופיעה בטבלת המיון לפי דירות'),
  ('1P', 107, 'apartment', '843', 'none', 'single', null),
  ('1P', 108, 'apartment', '1246', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 109, 'apartment', '533', 'none', 'single', null),
  ('1P', 110, 'apartment', '530', 'none', 'double_width', null),
  ('1P', 111, 'developer', null, 'none', 'single', null),
  ('1P', 112, 'developer', null, 'none', 'single', null),
  ('1P', 113, 'apartment', '634', 'none', 'double_width', null),
  ('1P', 114, 'apartment', '1246', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 115, 'apartment', '741', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 116, 'apartment', '1423', 'in_process', 'single', 'בתהליך רכישה; בדיקה: 116/163 — 1423 מול 1235'),
  ('1P', 117, 'apartment', '1341', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 118, 'committee', null, 'for_sale', 'single', null),
  ('1P', 119, 'apartment', '830', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 120, 'committee', null, 'for_sale', 'single', null),
  ('1P', 121, 'apartment', '737', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 122, 'committee', null, 'for_sale', 'single', null),
  ('1P', 123, 'committee', null, 'for_sale', 'single', null),
  ('1P', 124, 'committee', null, 'for_sale', 'single', null),
  ('1P', 125, 'committee', null, 'for_sale', 'single', null),
  ('1P', 126, 'committee', null, 'for_sale', 'single', null),
  ('1P', 127, 'committee', null, 'for_sale', 'single', null),
  ('1P', 128, 'apartment', '1539', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 129, 'committee', null, 'for_sale', 'single', null),
  ('1P', 130, 'committee', null, 'for_sale', 'single', null),
  ('1P', 131, 'committee', null, 'for_sale', 'single', null),
  ('1P', 132, 'committee', null, 'for_sale', 'single', null),
  ('1P', 133, 'committee', null, 'for_sale', 'single', null),
  ('1P', 134, 'committee', null, 'for_sale', 'single', null),
  ('1P', 135, 'developer', null, 'none', 'single', null),
  ('1P', 136, 'developer', null, 'none', 'single', null),
  ('1P', 137, 'apartment', '815', 'none', 'single', null),
  ('1P', 138, 'apartment', '1627', 'none', 'single', null),
  ('1P', 139, 'apartment', '815', 'none', 'single', null),
  ('1P', 140, 'apartment', '1206', 'none', 'single', null),
  ('1P', 141, 'apartment', '818', 'none', 'single', null),
  ('1P', 142, 'apartment', '1114', 'none', 'single', null),
  ('1P', 143, 'apartment', '514', 'none', 'single', null),
  ('1P', 144, 'apartment', '1017', 'sold', 'single', 'נמכרה ע"י הנציגות'),
  ('1P', 145, 'apartment', '1212', 'in_process', 'single', 'בתהליך רכישה'),
  ('1P', 146, 'apartment', '1235', 'in_process', 'single', 'בתהליך רכישה'),
  ('1P', 147, 'apartment', '805', 'none', 'single', null),
  ('1P', 148, 'apartment', '517', 'none', 'single', null),
  ('1P', 149, 'apartment', '1002', 'none', 'single', null),
  ('1P', 150, 'apartment', '703', 'in_process', 'single', 'בתהליך רכישה'),
  ('1P', 151, 'apartment', '1013', 'none', 'single', null),
  ('1P', 152, 'apartment', '1014', 'none', 'single', null),
  ('1P', 153, 'apartment', '801', 'none', 'single', null),
  ('1P', 154, 'apartment', '1407', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 155, 'apartment', '1009', 'none', 'single', null),
  ('1P', 156, 'apartment', '1101', 'none', 'single', null),
  ('1P', 157, 'apartment', '1539', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 158, 'apartment', '1243', 'none', 'single', null),
  ('1P', 159, 'apartment', '721', 'none', 'single', null),
  ('1P', 160, 'apartment', '1407', 'none', 'single', 'דירה שטרם נמכרה ע"י חוף הכרמל'),
  ('1P', 161, 'apartment', '546', 'none', 'single', null),
  ('1P', 162, 'apartment', '842', 'none', 'single', null),
  ('1P', 163, 'apartment', '1235', 'none', 'single', 'בדיקה: 116/163 — 1423 מול 1235'),
  ('1P', 164, 'apartment', '1027', 'none', 'single', null),
  ('1P', 165, 'apartment', '1134', 'none', 'single', null),
  ('1P', 166, 'apartment', '1524', 'none', 'single', null),
  ('1P', 167, 'apartment', '836', 'none', 'single', null),
  ('1P', 168, 'apartment', '629', 'none', 'single', null),
  ('1P', 169, 'apartment', '1526', 'none', 'single', null),
  ('1P', 170, 'apartment', '643', 'none', 'single', null),
  ('1P', 171, 'apartment', '746', 'none', 'single', null),
  ('1P', 172, 'apartment', '1142', 'none', 'single', null),
  ('1P', 173, 'apartment', '733', 'none', 'single', null),
  ('1P', 174, 'apartment', '1639', 'none', 'single', null),
  ('1P', 175, 'apartment', '1639', 'none', 'single', null),
  ('1P', 176, 'developer', null, 'none', 'single', null),
  ('1P', 177, 'developer', null, 'none', 'single', null),
  ('1P', 178, 'developer', null, 'none', 'single', null),
  ('1P', 179, 'developer', null, 'none', 'single', null),
  ('1P', 180, 'developer', null, 'none', 'single', null),
  ('1P', 181, 'developer', null, 'none', 'single', null),
  ('1P', 182, 'developer', null, 'none', 'single', null),
  ('1P', 183, 'developer', null, 'none', 'single', null),
  ('1P', 184, 'developer', null, 'none', 'single', null),
  ('1P', 185, 'developer', null, 'none', 'single', null),
  ('1P', 186, 'developer', null, 'none', 'single', null),
  ('1P', 187, 'developer', null, 'none', 'single', null)
on conflict (lot_code, spot_number) do nothing;

commit;
